--- origin/makefile  2017-08-13 07:59:27.189079901 +0000
+++ makefile    2017-08-13 08:03:10.094816330 +0000
@@ -3,7 +3,6 @@

 # List of local tools we need to build
 TOOLS := usergroupgen
-MKBOOTIMG_MK ?= $(shell pwd)/mkbootimg.mk
 IMG2SIMG_MK ?= $(shell pwd)/img2simg.mk
 SIMG2IMG_MK ?= $(shell pwd)/simg2img.mk

@@ -16,11 +15,9 @@
 all: $(TOOLS) image_tools

 image_tools:
-       make -f $(MKBOOTIMG_MK) -C $(ANDROID_ROOT)/system/core/mkbootimg/
        make -f $(IMG2SIMG_MK) -C $(ANDROID_ROOT)/system/core/libsparse/
        make -f $(SIMG2IMG_MK) -C $(ANDROID_ROOT)/system/core/libsparse/
 clean:
-       rm -f $(TOOLS) $(ANDROID_ROOT)/system/core/mkbootimg/mkbootimg \
        $(ANDROID_ROOT)/system/core/libsparse/img2simg \
        $(ANDROID_ROOT)/system/core/libsparse/simg2img
